## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print("Basic slicing, arr[2:7]")
print("with step", arr[1:8:2])
print("Negative indexing", arr[-3])


Basic slicing, arr[2:7]
with step [2 4]
Negative indexing 3


In [3]:
arr_2d =np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("specific element ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])



specific element  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [4]:
unsorted = np.array([3,1,4,1,5,9,2,6,5,3,5])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column: ", np.sort(arr_2d_unsorted, axis = 0))


Sorted array:  [1 1 2 3 3 4 5 5 5 6 9]
sorted 2d array by column:  [[1 1]
 [2 2]
 [3 3]]


## Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ", even_numbers)


Even numbers:  [ 2  4  6  8 10]


### Filter with mask

In [6]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])


Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where = np.where(numbers > 5)
print(where)
print("NP where: ", numbers[where])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, "True" , "False")
print(condition_array)


['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and Removeing data

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print("Combined array: ", combined)


Combined array:  [1 2 3 4 5 6]


### Array compatibilty

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9]) 

print("compatibility shapes: ", a.shape == b.shape)

compatibility shapes:  False


In [11]:
original = np.array([[1,2],[4,5]])
new_row = np.array([[3,4]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[6],[7]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)


[[1 2]
 [4 5]]
[[1 2]
 [4 5]
 [3 4]]
[[1 2 6]
 [4 5 7]]


In [12]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)  # delete element at index 2
print("Deleted element: ", deleted)


Deleted element:  [1 2 4 5 6]
