## numpy array and basics
learn about numpy with chai aurcode

In [1]:
import numpy as np

### creating array from list


In [2]:
arr_1 = np.array([1,2,3,4,5])
print("1D array:", arr_1)

arr_2 = np.array([[1,2,3],[4,5,6]])
print("2D array:\n", arr_2)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1,2,3]
print("python List multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #element-wise multiplication
print("numpy array multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("Numpy operation time: ", time.time() - start)

python List multiplication:  [1, 2, 3, 1, 2, 3]
numpy array multiplication:  [2 4 6]

 List operation time:  0.07765746116638184
Numpy operation time:  0.005597114562988281


### ceating from scratch

In [4]:
zeros = np.zeros((3,4))
print("Zeros array:\n", zeros)

ones = np.ones((2,3))
print("Ones array:\n", ones)

full = np.full((2,3), 5)
print("Full array:\n", full)

random = np.random.random((2,3))
print("Random array:\n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array:\n", sequence)



Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array:
 [[5 5 5]
 [5 5 5]]
Random array:
 [[0.04775098 0.66711466 0.08592296]
 [0.5265058  0.0051443  0.02560758]]
Sequence array:
 [0 2 4 6 8]


### vector , matrix and tensor

In [5]:
vector = np.array([1,2,3])
print("Vector:\n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:\n", matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor:\n", tensor)


Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties 

In [6]:
arr = np.array([[1,2,3],[4,5,6]])

print('shape:', arr.shape) 
print('ndim:', arr.ndim) 
print('size:', arr.size) 
print('dtype:', arr.dtype) 

shape: (2, 3)
ndim: 2
size: 6
dtype: int64


### Array reshaping

In [7]:
arr = np.arange(12)
print('Original array:', arr)

reshaped = arr.reshape(3, 4)
print('Reshaped array:\n', reshaped)

flattened = reshaped.flatten()
print('Flattened array:', flattened)

#reveled (returns view , instead of copy)

raveled = reshaped.ravel()
print('Raveled array:', raveled)

transposed = reshaped.T
print('Transposed array:\n', transposed)



Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
